// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/chatNcall_svc/infrastructure/pb/chatNcall.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUserChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderID   string               `protobuf:"bytes,1,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	RecieverID string               `protobuf:"bytes,2,opt,name=RecieverID,proto3" json:"RecieverID,omitempty"`
	Content    string               `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Status     string               `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	SentTime   *timestamp.Timestamp `protobuf:"bytes,5,opt,name=SentTime,proto3" json:"SentTime,omitempty"`
}

func (x *RequestUserChat) Reset() {
	*x = RequestUserChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUserChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUserChat) ProtoMessage() {}

func (x *RequestUserChat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUserChat.ProtoReflect.Descriptor instead.
func (*RequestUserChat) Descriptor() ([]byte, []int) {
	return file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUserChat) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

func (x *RequestUserChat) GetRecieverID() string {
	if x != nil {
		return x.RecieverID
	}
	return ""
}

func (x *RequestUserChat) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RequestUserChat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestUserChat) GetSentTime() *timestamp.Timestamp {
	if x != nil {
		return x.SentTime
	}
	return nil
}

type ResponseUserChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageID    string `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
}

func (x *ResponseUserChat) Reset() {
	*x = ResponseUserChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUserChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUserChat) ProtoMessage() {}

func (x *ResponseUserChat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUserChat.ProtoReflect.Descriptor instead.
func (*ResponseUserChat) Descriptor() ([]byte, []int) {
	return file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseUserChat) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *ResponseUserChat) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto protoreflect.FileDescriptor

var file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDesc = []byte{
	0x0a, 0x33, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x63, 0x61, 0x6c, 0x6c, 0x5f,
	0x73, 0x76, 0x63, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x69, 0x65,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x63,
	0x69, 0x65, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x53, 0x65, 0x6e,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x54, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x68, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x70, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74, 0x4e,
	0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x15, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x4f, 0x6e, 0x65, 0x54, 0x6f, 0x4f, 0x6e, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x54, 0x6f, 0x44, 0x42, 0x12, 0x20, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x63, 0x61,
	0x6c, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x42, 0x27, 0x5a, 0x25, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x76, 0x63,
	0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescOnce sync.Once
	file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescData = file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDesc
)

func file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescGZIP() []byte {
	file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescOnce.Do(func() {
		file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescData)
	})
	return file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDescData
}

var file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_goTypes = []interface{}{
	(*RequestUserChat)(nil),     // 0: chatNcall_proto.RequestUserChat
	(*ResponseUserChat)(nil),    // 1: chatNcall_proto.ResponseUserChat
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_depIdxs = []int32{
	2, // 0: chatNcall_proto.RequestUserChat.SentTime:type_name -> google.protobuf.Timestamp
	0, // 1: chatNcall_proto.ChatNCallService.StoreOneToOneChatToDB:input_type -> chatNcall_proto.RequestUserChat
	1, // 2: chatNcall_proto.ChatNCallService.StoreOneToOneChatToDB:output_type -> chatNcall_proto.ResponseUserChat
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_init() }
func file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_init() {
	if File_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUserChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUserChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_goTypes,
		DependencyIndexes: file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_depIdxs,
		MessageInfos:      file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_msgTypes,
	}.Build()
	File_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto = out.File
	file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_rawDesc = nil
	file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_goTypes = nil
	file_pkg_chatNcall_svc_infrastructure_pb_chatNcall_proto_depIdxs = nil
}
