// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/postNrelation_svc/infrastructure/pb/postnrel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUserIdOnly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *RequestUserIdOnly) Reset() {
	*x = RequestUserIdOnly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUserIdOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUserIdOnly) ProtoMessage() {}

func (x *RequestUserIdOnly) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUserIdOnly.ProtoReflect.Descriptor instead.
func (*RequestUserIdOnly) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUserIdOnly) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResponseErrorMessageOnly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
}

func (x *ResponseErrorMessageOnly) Reset() {
	*x = ResponseErrorMessageOnly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseErrorMessageOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseErrorMessageOnly) ProtoMessage() {}

func (x *ResponseErrorMessageOnly) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseErrorMessageOnly.ProtoReflect.Descriptor instead.
func (*ResponseErrorMessageOnly) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseErrorMessageOnly) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RequestFollowUnFollow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserBId string `protobuf:"bytes,2,opt,name=UserBId,proto3" json:"UserBId,omitempty"`
}

func (x *RequestFollowUnFollow) Reset() {
	*x = RequestFollowUnFollow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFollowUnFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFollowUnFollow) ProtoMessage() {}

func (x *RequestFollowUnFollow) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFollowUnFollow.ProtoReflect.Descriptor instead.
func (*RequestFollowUnFollow) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{2}
}

func (x *RequestFollowUnFollow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestFollowUnFollow) GetUserBId() string {
	if x != nil {
		return x.UserBId
	}
	return ""
}

type RequestEditPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId  string `protobuf:"bytes,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Caption string `protobuf:"bytes,3,opt,name=Caption,proto3" json:"Caption,omitempty"`
}

func (x *RequestEditPost) Reset() {
	*x = RequestEditPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEditPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEditPost) ProtoMessage() {}

func (x *RequestEditPost) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEditPost.ProtoReflect.Descriptor instead.
func (*RequestEditPost) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{3}
}

func (x *RequestEditPost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestEditPost) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *RequestEditPost) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type RequestDeletePost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId string `protobuf:"bytes,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *RequestDeletePost) Reset() {
	*x = RequestDeletePost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeletePost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeletePost) ProtoMessage() {}

func (x *RequestDeletePost) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeletePost.ProtoReflect.Descriptor instead.
func (*RequestDeletePost) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{4}
}

func (x *RequestDeletePost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestDeletePost) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type PostsDataModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName          string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	UserProfileImgURL string   `protobuf:"bytes,3,opt,name=UserProfileImgURL,proto3" json:"UserProfileImgURL,omitempty"`
	PostId            uint64   `protobuf:"varint,4,opt,name=PostId,proto3" json:"PostId,omitempty"`
	LikeStatus        bool     `protobuf:"varint,5,opt,name=LikeStatus,proto3" json:"LikeStatus,omitempty"`
	Caption           string   `protobuf:"bytes,6,opt,name=Caption,proto3" json:"Caption,omitempty"`
	LikesCount        string   `protobuf:"bytes,7,opt,name=LikesCount,proto3" json:"LikesCount,omitempty"`
	CommentsCount     string   `protobuf:"bytes,8,opt,name=CommentsCount,proto3" json:"CommentsCount,omitempty"`
	PostAge           string   `protobuf:"bytes,9,opt,name=PostAge,proto3" json:"PostAge,omitempty"`
	MediaUrl          []string `protobuf:"bytes,10,rep,name=MediaUrl,proto3" json:"MediaUrl,omitempty"`
}

func (x *PostsDataModel) Reset() {
	*x = PostsDataModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostsDataModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsDataModel) ProtoMessage() {}

func (x *PostsDataModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsDataModel.ProtoReflect.Descriptor instead.
func (*PostsDataModel) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{5}
}

func (x *PostsDataModel) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostsDataModel) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PostsDataModel) GetUserProfileImgURL() string {
	if x != nil {
		return x.UserProfileImgURL
	}
	return ""
}

func (x *PostsDataModel) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostsDataModel) GetLikeStatus() bool {
	if x != nil {
		return x.LikeStatus
	}
	return false
}

func (x *PostsDataModel) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *PostsDataModel) GetLikesCount() string {
	if x != nil {
		return x.LikesCount
	}
	return ""
}

func (x *PostsDataModel) GetCommentsCount() string {
	if x != nil {
		return x.CommentsCount
	}
	return ""
}

func (x *PostsDataModel) GetPostAge() string {
	if x != nil {
		return x.PostAge
	}
	return ""
}

func (x *PostsDataModel) GetMediaUrl() []string {
	if x != nil {
		return x.MediaUrl
	}
	return nil
}

type RequestGetAllPosts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Limit  string `protobuf:"bytes,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	OffSet string `protobuf:"bytes,3,opt,name=OffSet,proto3" json:"OffSet,omitempty"`
}

func (x *RequestGetAllPosts) Reset() {
	*x = RequestGetAllPosts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetAllPosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetAllPosts) ProtoMessage() {}

func (x *RequestGetAllPosts) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetAllPosts.ProtoReflect.Descriptor instead.
func (*RequestGetAllPosts) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{6}
}

func (x *RequestGetAllPosts) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestGetAllPosts) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *RequestGetAllPosts) GetOffSet() string {
	if x != nil {
		return x.OffSet
	}
	return ""
}

type ResponseUserPosts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostsData    []*PostsDataModel `protobuf:"bytes,1,rep,name=PostsData,proto3" json:"PostsData,omitempty"`
	ErrorMessage string            `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
}

func (x *ResponseUserPosts) Reset() {
	*x = ResponseUserPosts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUserPosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUserPosts) ProtoMessage() {}

func (x *ResponseUserPosts) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUserPosts.ProtoReflect.Descriptor instead.
func (*ResponseUserPosts) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseUserPosts) GetPostsData() []*PostsDataModel {
	if x != nil {
		return x.PostsData
	}
	return nil
}

func (x *ResponseUserPosts) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SingleMedia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media       []byte `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	ContentType string `protobuf:"bytes,2,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
}

func (x *SingleMedia) Reset() {
	*x = SingleMedia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMedia) ProtoMessage() {}

func (x *SingleMedia) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMedia.ProtoReflect.Descriptor instead.
func (*SingleMedia) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{8}
}

func (x *SingleMedia) GetMedia() []byte {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *SingleMedia) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type RequestAddPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string         `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Caption string         `protobuf:"bytes,2,opt,name=Caption,proto3" json:"Caption,omitempty"`
	Media   []*SingleMedia `protobuf:"bytes,3,rep,name=Media,proto3" json:"Media,omitempty"`
}

func (x *RequestAddPost) Reset() {
	*x = RequestAddPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAddPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddPost) ProtoMessage() {}

func (x *RequestAddPost) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddPost.ProtoReflect.Descriptor instead.
func (*RequestAddPost) Descriptor() ([]byte, []int) {
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP(), []int{9}
}

func (x *RequestAddPost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestAddPost) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *RequestAddPost) GetMedia() []*SingleMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto protoreflect.FileDescriptor

var file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDesc = []byte{
	0x0a, 0x36, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x4e, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x76, 0x63, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72,
	0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x18, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e, 0x6c,
	0x79, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x49, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x6e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x42, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x42, 0x49, 0x64,
	0x22, 0x5b, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x64, 0x69, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a,
	0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x22, 0xc0, 0x02, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6d, 0x67, 0x55, 0x52, 0x4c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x6d, 0x67, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x69, 0x6b,
	0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x55, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x55, 0x72, 0x6c, 0x22, 0x5a, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66,
	0x53, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x53, 0x65,
	0x74, 0x22, 0x75, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x45, 0x0a, 0x0b, 0x73, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x75, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x61, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x61, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x32, 0xae, 0x04, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x4e,
	0x72, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x4e, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e,
	0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e,
	0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e,
	0x6c, 0x79, 0x12, 0x59, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65,
	0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x1a, 0x21, 0x2e, 0x70, 0x6f, 0x73,
	0x74, 0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x59, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x6f,
	0x73, 0x74, 0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x55, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65, 0x6c, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x64, 0x69,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65, 0x6c,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x12,
	0x59, 0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x25, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x6e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x1a, 0x28, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x5b, 0x0a, 0x08, 0x55, 0x6e,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x25, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65,
	0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x6e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x1a, 0x28, 0x2e,
	0x70, 0x6f, 0x73, 0x74, 0x6e, 0x72, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x42, 0x2b, 0x5a, 0x29, 0x2e, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x6f, 0x73, 0x74, 0x4e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x76, 0x63, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescOnce sync.Once
	file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescData = file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDesc
)

func file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescGZIP() []byte {
	file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescOnce.Do(func() {
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescData)
	})
	return file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDescData
}

var file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_goTypes = []interface{}{
	(*RequestUserIdOnly)(nil),        // 0: postnrel_proto.RequestUserIdOnly
	(*ResponseErrorMessageOnly)(nil), // 1: postnrel_proto.ResponseErrorMessageOnly
	(*RequestFollowUnFollow)(nil),    // 2: postnrel_proto.RequestFollowUnFollow
	(*RequestEditPost)(nil),          // 3: postnrel_proto.RequestEditPost
	(*RequestDeletePost)(nil),        // 4: postnrel_proto.RequestDeletePost
	(*PostsDataModel)(nil),           // 5: postnrel_proto.PostsDataModel
	(*RequestGetAllPosts)(nil),       // 6: postnrel_proto.RequestGetAllPosts
	(*ResponseUserPosts)(nil),        // 7: postnrel_proto.ResponseUserPosts
	(*SingleMedia)(nil),              // 8: postnrel_proto.singleMedia
	(*RequestAddPost)(nil),           // 9: postnrel_proto.RequestAddPost
}
var file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_depIdxs = []int32{
	5, // 0: postnrel_proto.ResponseUserPosts.PostsData:type_name -> postnrel_proto.PostsDataModel
	8, // 1: postnrel_proto.RequestAddPost.Media:type_name -> postnrel_proto.singleMedia
	9, // 2: postnrel_proto.PostNrelService.AddNewPost:input_type -> postnrel_proto.RequestAddPost
	6, // 3: postnrel_proto.PostNrelService.GetAllPostByUser:input_type -> postnrel_proto.RequestGetAllPosts
	4, // 4: postnrel_proto.PostNrelService.DeletePost:input_type -> postnrel_proto.RequestDeletePost
	3, // 5: postnrel_proto.PostNrelService.EditPost:input_type -> postnrel_proto.RequestEditPost
	2, // 6: postnrel_proto.PostNrelService.Follow:input_type -> postnrel_proto.RequestFollowUnFollow
	2, // 7: postnrel_proto.PostNrelService.UnFollow:input_type -> postnrel_proto.RequestFollowUnFollow
	1, // 8: postnrel_proto.PostNrelService.AddNewPost:output_type -> postnrel_proto.ResponseErrorMessageOnly
	7, // 9: postnrel_proto.PostNrelService.GetAllPostByUser:output_type -> postnrel_proto.ResponseUserPosts
	1, // 10: postnrel_proto.PostNrelService.DeletePost:output_type -> postnrel_proto.ResponseErrorMessageOnly
	1, // 11: postnrel_proto.PostNrelService.EditPost:output_type -> postnrel_proto.ResponseErrorMessageOnly
	1, // 12: postnrel_proto.PostNrelService.Follow:output_type -> postnrel_proto.ResponseErrorMessageOnly
	1, // 13: postnrel_proto.PostNrelService.UnFollow:output_type -> postnrel_proto.ResponseErrorMessageOnly
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_init() }
func file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_init() {
	if File_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUserIdOnly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseErrorMessageOnly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFollowUnFollow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEditPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeletePost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostsDataModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetAllPosts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUserPosts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMedia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAddPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_goTypes,
		DependencyIndexes: file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_depIdxs,
		MessageInfos:      file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_msgTypes,
	}.Build()
	File_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto = out.File
	file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_rawDesc = nil
	file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_goTypes = nil
	file_pkg_postNrelation_svc_infrastructure_pb_postnrel_proto_depIdxs = nil
}
